// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grpc_exec/grpc_exec.proto

package grpcexecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ClientEvent_Start
	//	*ClientEvent_Terminate
	Event         isClientEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{0}
}

func (x *ClientEvent) GetEvent() isClientEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ClientEvent) GetStart() *StartCommandRequest {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ClientEvent) GetTerminate() *TerminateCommand {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Terminate); ok {
			return x.Terminate
		}
	}
	return nil
}

type isClientEvent_Event interface {
	isClientEvent_Event()
}

type ClientEvent_Start struct {
	// Must be the first message on the stream.
	Start *StartCommandRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ClientEvent_Terminate struct {
	// Request termination of the running command.
	Terminate *TerminateCommand `protobuf:"bytes,2,opt,name=terminate,proto3,oneof"`
}

func (*ClientEvent_Start) isClientEvent_Event() {}

func (*ClientEvent_Terminate) isClientEvent_Event() {}

type StartCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw shell command to execute.
	CommandLine string `protobuf:"bytes,1,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	// The directory to execute the command in.
	WorkingDir    string `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCommandRequest) Reset() {
	*x = StartCommandRequest{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCommandRequest) ProtoMessage() {}

func (x *StartCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCommandRequest.ProtoReflect.Descriptor instead.
func (*StartCommandRequest) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{1}
}

func (x *StartCommandRequest) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *StartCommandRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type TerminateCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When false, send SIGTERM only (grace_period is ignored).
	// When true, guarantee the process dies via SIGKILL. If grace_period
	// is set, send SIGTERM first and SIGKILL after the grace period;
	// otherwise send SIGKILL immediately.
	Force bool `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	// Only used when force is true. If non-zero, SIGTERM is sent first
	// and SIGKILL follows after this duration.
	GracePeriod   *durationpb.Duration `protobuf:"bytes,2,opt,name=grace_period,json=gracePeriod,proto3" json:"grace_period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateCommand) Reset() {
	*x = TerminateCommand{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateCommand) ProtoMessage() {}

func (x *TerminateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateCommand.ProtoReflect.Descriptor instead.
func (*TerminateCommand) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{2}
}

func (x *TerminateCommand) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *TerminateCommand) GetGracePeriod() *durationpb.Duration {
	if x != nil {
		return x.GracePeriod
	}
	return nil
}

type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_Output
	//	*ServerEvent_Exited
	//	*ServerEvent_Started
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{3}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetOutput() []byte {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *ServerEvent) GetExited() *ExitInfo {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

func (x *ServerEvent) GetStarted() *CommandStarted {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_Output struct {
	// Incremental stdout/stderr from the command.
	Output []byte `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type ServerEvent_Exited struct {
	// Sent exactly once when the command finishes.
	Exited *ExitInfo `protobuf:"bytes,2,opt,name=exited,proto3,oneof"`
}

type ServerEvent_Started struct {
	// Sent once after the command starts, before any output.
	Started *CommandStarted `protobuf:"bytes,3,opt,name=started,proto3,oneof"`
}

func (*ServerEvent_Output) isServerEvent_Event() {}

func (*ServerEvent_Exited) isServerEvent_Event() {}

func (*ServerEvent_Started) isServerEvent_Event() {}

type CommandStarted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier for this command invocation.
	CommandId     string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandStarted) Reset() {
	*x = CommandStarted{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandStarted) ProtoMessage() {}

func (x *CommandStarted) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandStarted.ProtoReflect.Descriptor instead.
func (*CommandStarted) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{4}
}

func (x *CommandStarted) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type ExitInfo struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ExitCode int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Populated only if the system failed to execute the command at all.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitInfo) Reset() {
	*x = ExitInfo{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitInfo) ProtoMessage() {}

func (x *ExitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitInfo.ProtoReflect.Descriptor instead.
func (*ExitInfo) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{5}
}

func (x *ExitInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExitInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type TunnelClientEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*TunnelClientEvent_Open
	//	*TunnelClientEvent_Data
	//	*TunnelClientEvent_Close
	Event         isTunnelClientEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelClientEvent) Reset() {
	*x = TunnelClientEvent{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelClientEvent) ProtoMessage() {}

func (x *TunnelClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelClientEvent.ProtoReflect.Descriptor instead.
func (*TunnelClientEvent) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{6}
}

func (x *TunnelClientEvent) GetEvent() isTunnelClientEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TunnelClientEvent) GetOpen() *OpenTcpRequest {
	if x != nil {
		if x, ok := x.Event.(*TunnelClientEvent_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *TunnelClientEvent) GetData() []byte {
	if x != nil {
		if x, ok := x.Event.(*TunnelClientEvent_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *TunnelClientEvent) GetClose() *CloseTunnel {
	if x != nil {
		if x, ok := x.Event.(*TunnelClientEvent_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isTunnelClientEvent_Event interface {
	isTunnelClientEvent_Event()
}

type TunnelClientEvent_Open struct {
	// Must be the first message on the stream.
	Open *OpenTcpRequest `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type TunnelClientEvent_Data struct {
	// Bytes to write to the remote connection.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type TunnelClientEvent_Close struct {
	// Close the active connection.
	Close *CloseTunnel `protobuf:"bytes,3,opt,name=close,proto3,oneof"`
}

func (*TunnelClientEvent_Open) isTunnelClientEvent_Event() {}

func (*TunnelClientEvent_Data) isTunnelClientEvent_Event() {}

func (*TunnelClientEvent_Close) isTunnelClientEvent_Event() {}

type OpenTcpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTcpRequest) Reset() {
	*x = OpenTcpRequest{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTcpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTcpRequest) ProtoMessage() {}

func (x *OpenTcpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTcpRequest.ProtoReflect.Descriptor instead.
func (*OpenTcpRequest) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{7}
}

func (x *OpenTcpRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OpenTcpRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CloseTunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTunnel) Reset() {
	*x = CloseTunnel{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnel) ProtoMessage() {}

func (x *CloseTunnel) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnel.ProtoReflect.Descriptor instead.
func (*CloseTunnel) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{8}
}

type TunnelServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*TunnelServerEvent_Opened
	//	*TunnelServerEvent_Data
	//	*TunnelServerEvent_Closed
	//	*TunnelServerEvent_Error
	Event         isTunnelServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelServerEvent) Reset() {
	*x = TunnelServerEvent{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelServerEvent) ProtoMessage() {}

func (x *TunnelServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelServerEvent.ProtoReflect.Descriptor instead.
func (*TunnelServerEvent) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{9}
}

func (x *TunnelServerEvent) GetEvent() isTunnelServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TunnelServerEvent) GetOpened() *TunnelOpened {
	if x != nil {
		if x, ok := x.Event.(*TunnelServerEvent_Opened); ok {
			return x.Opened
		}
	}
	return nil
}

func (x *TunnelServerEvent) GetData() []byte {
	if x != nil {
		if x, ok := x.Event.(*TunnelServerEvent_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *TunnelServerEvent) GetClosed() *TunnelClosed {
	if x != nil {
		if x, ok := x.Event.(*TunnelServerEvent_Closed); ok {
			return x.Closed
		}
	}
	return nil
}

func (x *TunnelServerEvent) GetError() *TunnelError {
	if x != nil {
		if x, ok := x.Event.(*TunnelServerEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTunnelServerEvent_Event interface {
	isTunnelServerEvent_Event()
}

type TunnelServerEvent_Opened struct {
	// Sent once when the TCP connection is established.
	Opened *TunnelOpened `protobuf:"bytes,1,opt,name=opened,proto3,oneof"`
}

type TunnelServerEvent_Data struct {
	// Bytes received from the remote connection.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type TunnelServerEvent_Closed struct {
	// Sent once when the connection is closed cleanly.
	Closed *TunnelClosed `protobuf:"bytes,3,opt,name=closed,proto3,oneof"`
}

type TunnelServerEvent_Error struct {
	// Sent on dialing/proxying failure before the stream ends.
	Error *TunnelError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*TunnelServerEvent_Opened) isTunnelServerEvent_Event() {}

func (*TunnelServerEvent_Data) isTunnelServerEvent_Event() {}

func (*TunnelServerEvent_Closed) isTunnelServerEvent_Event() {}

func (*TunnelServerEvent_Error) isTunnelServerEvent_Event() {}

type TunnelOpened struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteAddress string                 `protobuf:"bytes,1,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"`
	RemotePort    uint32                 `protobuf:"varint,2,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelOpened) Reset() {
	*x = TunnelOpened{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelOpened) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelOpened) ProtoMessage() {}

func (x *TunnelOpened) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelOpened.ProtoReflect.Descriptor instead.
func (*TunnelOpened) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{10}
}

func (x *TunnelOpened) GetRemoteAddress() string {
	if x != nil {
		return x.RemoteAddress
	}
	return ""
}

func (x *TunnelOpened) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

type TunnelClosed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelClosed) Reset() {
	*x = TunnelClosed{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelClosed) ProtoMessage() {}

func (x *TunnelClosed) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelClosed.ProtoReflect.Descriptor instead.
func (*TunnelClosed) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{11}
}

func (x *TunnelClosed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TunnelError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelError) Reset() {
	*x = TunnelError{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelError) ProtoMessage() {}

func (x *TunnelError) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelError.ProtoReflect.Descriptor instead.
func (*TunnelError) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{12}
}

func (x *TunnelError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_exec_grpc_exec_proto protoreflect.FileDescriptor

const file_grpc_exec_grpc_exec_proto_rawDesc = "" +
	"\n" +
	"\x19grpc_exec/grpc_exec.proto\x12\tgrpc_exec\x1a\x1egoogle/protobuf/duration.proto\"\x8b\x01\n" +
	"\vClientEvent\x126\n" +
	"\x05start\x18\x01 \x01(\v2\x1e.grpc_exec.StartCommandRequestH\x00R\x05start\x12;\n" +
	"\tterminate\x18\x02 \x01(\v2\x1b.grpc_exec.TerminateCommandH\x00R\tterminateB\a\n" +
	"\x05event\"Y\n" +
	"\x13StartCommandRequest\x12!\n" +
	"\fcommand_line\x18\x01 \x01(\tR\vcommandLine\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\"f\n" +
	"\x10TerminateCommand\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\x12<\n" +
	"\fgrace_period\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vgracePeriod\"\x96\x01\n" +
	"\vServerEvent\x12\x18\n" +
	"\x06output\x18\x01 \x01(\fH\x00R\x06output\x12-\n" +
	"\x06exited\x18\x02 \x01(\v2\x13.grpc_exec.ExitInfoH\x00R\x06exited\x125\n" +
	"\astarted\x18\x03 \x01(\v2\x19.grpc_exec.CommandStartedH\x00R\astartedB\a\n" +
	"\x05event\"/\n" +
	"\x0eCommandStarted\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"L\n" +
	"\bExitInfo\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x93\x01\n" +
	"\x11TunnelClientEvent\x12/\n" +
	"\x04open\x18\x01 \x01(\v2\x19.grpc_exec.OpenTcpRequestH\x00R\x04open\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12.\n" +
	"\x05close\x18\x03 \x01(\v2\x16.grpc_exec.CloseTunnelH\x00R\x05closeB\a\n" +
	"\x05event\">\n" +
	"\x0eOpenTcpRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\r\n" +
	"\vCloseTunnel\"\xc8\x01\n" +
	"\x11TunnelServerEvent\x121\n" +
	"\x06opened\x18\x01 \x01(\v2\x17.grpc_exec.TunnelOpenedH\x00R\x06opened\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x121\n" +
	"\x06closed\x18\x03 \x01(\v2\x17.grpc_exec.TunnelClosedH\x00R\x06closed\x12.\n" +
	"\x05error\x18\x04 \x01(\v2\x16.grpc_exec.TunnelErrorH\x00R\x05errorB\a\n" +
	"\x05event\"V\n" +
	"\fTunnelOpened\x12%\n" +
	"\x0eremote_address\x18\x01 \x01(\tR\rremoteAddress\x12\x1f\n" +
	"\vremote_port\x18\x02 \x01(\rR\n" +
	"remotePort\"&\n" +
	"\fTunnelClosed\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"'\n" +
	"\vTunnelError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2O\n" +
	"\vExecService\x12@\n" +
	"\n" +
	"RunCommand\x12\x16.grpc_exec.ClientEvent\x1a\x16.grpc_exec.ServerEvent(\x010\x012Z\n" +
	"\rTunnelService\x12I\n" +
	"\aOpenTcp\x12\x1c.grpc_exec.TunnelClientEvent\x1a\x1c.grpc_exec.TunnelServerEvent(\x010\x01B+Z)github.com/maceip/v9/grpc_exec/grpcexecpbb\x06proto3"

var (
	file_grpc_exec_grpc_exec_proto_rawDescOnce sync.Once
	file_grpc_exec_grpc_exec_proto_rawDescData []byte
)

func file_grpc_exec_grpc_exec_proto_rawDescGZIP() []byte {
	file_grpc_exec_grpc_exec_proto_rawDescOnce.Do(func() {
		file_grpc_exec_grpc_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_exec_grpc_exec_proto_rawDesc), len(file_grpc_exec_grpc_exec_proto_rawDesc)))
	})
	return file_grpc_exec_grpc_exec_proto_rawDescData
}

var file_grpc_exec_grpc_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_grpc_exec_grpc_exec_proto_goTypes = []any{
	(*ClientEvent)(nil),         // 0: grpc_exec.ClientEvent
	(*StartCommandRequest)(nil), // 1: grpc_exec.StartCommandRequest
	(*TerminateCommand)(nil),    // 2: grpc_exec.TerminateCommand
	(*ServerEvent)(nil),         // 3: grpc_exec.ServerEvent
	(*CommandStarted)(nil),      // 4: grpc_exec.CommandStarted
	(*ExitInfo)(nil),            // 5: grpc_exec.ExitInfo
	(*TunnelClientEvent)(nil),   // 6: grpc_exec.TunnelClientEvent
	(*OpenTcpRequest)(nil),      // 7: grpc_exec.OpenTcpRequest
	(*CloseTunnel)(nil),         // 8: grpc_exec.CloseTunnel
	(*TunnelServerEvent)(nil),   // 9: grpc_exec.TunnelServerEvent
	(*TunnelOpened)(nil),        // 10: grpc_exec.TunnelOpened
	(*TunnelClosed)(nil),        // 11: grpc_exec.TunnelClosed
	(*TunnelError)(nil),         // 12: grpc_exec.TunnelError
	(*durationpb.Duration)(nil), // 13: google.protobuf.Duration
}
var file_grpc_exec_grpc_exec_proto_depIdxs = []int32{
	1,  // 0: grpc_exec.ClientEvent.start:type_name -> grpc_exec.StartCommandRequest
	2,  // 1: grpc_exec.ClientEvent.terminate:type_name -> grpc_exec.TerminateCommand
	13, // 2: grpc_exec.TerminateCommand.grace_period:type_name -> google.protobuf.Duration
	5,  // 3: grpc_exec.ServerEvent.exited:type_name -> grpc_exec.ExitInfo
	4,  // 4: grpc_exec.ServerEvent.started:type_name -> grpc_exec.CommandStarted
	7,  // 5: grpc_exec.TunnelClientEvent.open:type_name -> grpc_exec.OpenTcpRequest
	8,  // 6: grpc_exec.TunnelClientEvent.close:type_name -> grpc_exec.CloseTunnel
	10, // 7: grpc_exec.TunnelServerEvent.opened:type_name -> grpc_exec.TunnelOpened
	11, // 8: grpc_exec.TunnelServerEvent.closed:type_name -> grpc_exec.TunnelClosed
	12, // 9: grpc_exec.TunnelServerEvent.error:type_name -> grpc_exec.TunnelError
	0,  // 10: grpc_exec.ExecService.RunCommand:input_type -> grpc_exec.ClientEvent
	6,  // 11: grpc_exec.TunnelService.OpenTcp:input_type -> grpc_exec.TunnelClientEvent
	3,  // 12: grpc_exec.ExecService.RunCommand:output_type -> grpc_exec.ServerEvent
	9,  // 13: grpc_exec.TunnelService.OpenTcp:output_type -> grpc_exec.TunnelServerEvent
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_grpc_exec_grpc_exec_proto_init() }
func file_grpc_exec_grpc_exec_proto_init() {
	if File_grpc_exec_grpc_exec_proto != nil {
		return
	}
	file_grpc_exec_grpc_exec_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientEvent_Start)(nil),
		(*ClientEvent_Terminate)(nil),
	}
	file_grpc_exec_grpc_exec_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerEvent_Output)(nil),
		(*ServerEvent_Exited)(nil),
		(*ServerEvent_Started)(nil),
	}
	file_grpc_exec_grpc_exec_proto_msgTypes[6].OneofWrappers = []any{
		(*TunnelClientEvent_Open)(nil),
		(*TunnelClientEvent_Data)(nil),
		(*TunnelClientEvent_Close)(nil),
	}
	file_grpc_exec_grpc_exec_proto_msgTypes[9].OneofWrappers = []any{
		(*TunnelServerEvent_Opened)(nil),
		(*TunnelServerEvent_Data)(nil),
		(*TunnelServerEvent_Closed)(nil),
		(*TunnelServerEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_exec_grpc_exec_proto_rawDesc), len(file_grpc_exec_grpc_exec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grpc_exec_grpc_exec_proto_goTypes,
		DependencyIndexes: file_grpc_exec_grpc_exec_proto_depIdxs,
		MessageInfos:      file_grpc_exec_grpc_exec_proto_msgTypes,
	}.Build()
	File_grpc_exec_grpc_exec_proto = out.File
	file_grpc_exec_grpc_exec_proto_goTypes = nil
	file_grpc_exec_grpc_exec_proto_depIdxs = nil
}
