// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grpc_exec/grpc_exec.proto

package grpcexecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ClientEvent_Start
	//	*ClientEvent_Terminate
	Event         isClientEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{0}
}

func (x *ClientEvent) GetEvent() isClientEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ClientEvent) GetStart() *StartCommandRequest {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ClientEvent) GetTerminate() *TerminateCommand {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Terminate); ok {
			return x.Terminate
		}
	}
	return nil
}

type isClientEvent_Event interface {
	isClientEvent_Event()
}

type ClientEvent_Start struct {
	// Must be the first message on the stream.
	Start *StartCommandRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ClientEvent_Terminate struct {
	// Request termination of the running command.
	Terminate *TerminateCommand `protobuf:"bytes,2,opt,name=terminate,proto3,oneof"`
}

func (*ClientEvent_Start) isClientEvent_Event() {}

func (*ClientEvent_Terminate) isClientEvent_Event() {}

type StartCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw shell command to execute.
	CommandLine string `protobuf:"bytes,1,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	// The directory to execute the command in.
	WorkingDir    string `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCommandRequest) Reset() {
	*x = StartCommandRequest{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCommandRequest) ProtoMessage() {}

func (x *StartCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCommandRequest.ProtoReflect.Descriptor instead.
func (*StartCommandRequest) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{1}
}

func (x *StartCommandRequest) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *StartCommandRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type TerminateCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When false, send SIGTERM only (grace_period is ignored).
	// When true, guarantee the process dies via SIGKILL. If grace_period
	// is set, send SIGTERM first and SIGKILL after the grace period;
	// otherwise send SIGKILL immediately.
	Force bool `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	// Only used when force is true. If non-zero, SIGTERM is sent first
	// and SIGKILL follows after this duration.
	GracePeriod   *durationpb.Duration `protobuf:"bytes,2,opt,name=grace_period,json=gracePeriod,proto3" json:"grace_period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateCommand) Reset() {
	*x = TerminateCommand{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateCommand) ProtoMessage() {}

func (x *TerminateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateCommand.ProtoReflect.Descriptor instead.
func (*TerminateCommand) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{2}
}

func (x *TerminateCommand) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *TerminateCommand) GetGracePeriod() *durationpb.Duration {
	if x != nil {
		return x.GracePeriod
	}
	return nil
}

type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_Output
	//	*ServerEvent_Exited
	//	*ServerEvent_Started
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{3}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetOutput() []byte {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *ServerEvent) GetExited() *ExitInfo {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

func (x *ServerEvent) GetStarted() *CommandStarted {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_Output struct {
	// Incremental stdout/stderr from the command.
	Output []byte `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type ServerEvent_Exited struct {
	// Sent exactly once when the command finishes.
	Exited *ExitInfo `protobuf:"bytes,2,opt,name=exited,proto3,oneof"`
}

type ServerEvent_Started struct {
	// Sent once after the command starts, before any output.
	Started *CommandStarted `protobuf:"bytes,3,opt,name=started,proto3,oneof"`
}

func (*ServerEvent_Output) isServerEvent_Event() {}

func (*ServerEvent_Exited) isServerEvent_Event() {}

func (*ServerEvent_Started) isServerEvent_Event() {}

type CommandStarted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier for this command invocation.
	CommandId     string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandStarted) Reset() {
	*x = CommandStarted{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandStarted) ProtoMessage() {}

func (x *CommandStarted) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandStarted.ProtoReflect.Descriptor instead.
func (*CommandStarted) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{4}
}

func (x *CommandStarted) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type ExitInfo struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ExitCode int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Populated only if the system failed to execute the command at all.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitInfo) Reset() {
	*x = ExitInfo{}
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitInfo) ProtoMessage() {}

func (x *ExitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exec_grpc_exec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitInfo.ProtoReflect.Descriptor instead.
func (*ExitInfo) Descriptor() ([]byte, []int) {
	return file_grpc_exec_grpc_exec_proto_rawDescGZIP(), []int{5}
}

func (x *ExitInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExitInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_grpc_exec_grpc_exec_proto protoreflect.FileDescriptor

const file_grpc_exec_grpc_exec_proto_rawDesc = "" +
	"\n" +
	"\x19grpc_exec/grpc_exec.proto\x12\tgrpc_exec\x1a\x1egoogle/protobuf/duration.proto\"\x8b\x01\n" +
	"\vClientEvent\x126\n" +
	"\x05start\x18\x01 \x01(\v2\x1e.grpc_exec.StartCommandRequestH\x00R\x05start\x12;\n" +
	"\tterminate\x18\x02 \x01(\v2\x1b.grpc_exec.TerminateCommandH\x00R\tterminateB\a\n" +
	"\x05event\"Y\n" +
	"\x13StartCommandRequest\x12!\n" +
	"\fcommand_line\x18\x01 \x01(\tR\vcommandLine\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\"f\n" +
	"\x10TerminateCommand\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\x12<\n" +
	"\fgrace_period\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vgracePeriod\"\x96\x01\n" +
	"\vServerEvent\x12\x18\n" +
	"\x06output\x18\x01 \x01(\fH\x00R\x06output\x12-\n" +
	"\x06exited\x18\x02 \x01(\v2\x13.grpc_exec.ExitInfoH\x00R\x06exited\x125\n" +
	"\astarted\x18\x03 \x01(\v2\x19.grpc_exec.CommandStartedH\x00R\astartedB\a\n" +
	"\x05event\"/\n" +
	"\x0eCommandStarted\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"L\n" +
	"\bExitInfo\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2O\n" +
	"\vExecService\x12@\n" +
	"\n" +
	"RunCommand\x12\x16.grpc_exec.ClientEvent\x1a\x16.grpc_exec.ServerEvent(\x010\x01B+Z)github.com/maceip/v9/grpc_exec/grpcexecpbb\x06proto3"

var (
	file_grpc_exec_grpc_exec_proto_rawDescOnce sync.Once
	file_grpc_exec_grpc_exec_proto_rawDescData []byte
)

func file_grpc_exec_grpc_exec_proto_rawDescGZIP() []byte {
	file_grpc_exec_grpc_exec_proto_rawDescOnce.Do(func() {
		file_grpc_exec_grpc_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_exec_grpc_exec_proto_rawDesc), len(file_grpc_exec_grpc_exec_proto_rawDesc)))
	})
	return file_grpc_exec_grpc_exec_proto_rawDescData
}

var file_grpc_exec_grpc_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_exec_grpc_exec_proto_goTypes = []any{
	(*ClientEvent)(nil),         // 0: grpc_exec.ClientEvent
	(*StartCommandRequest)(nil), // 1: grpc_exec.StartCommandRequest
	(*TerminateCommand)(nil),    // 2: grpc_exec.TerminateCommand
	(*ServerEvent)(nil),         // 3: grpc_exec.ServerEvent
	(*CommandStarted)(nil),      // 4: grpc_exec.CommandStarted
	(*ExitInfo)(nil),            // 5: grpc_exec.ExitInfo
	(*durationpb.Duration)(nil), // 6: google.protobuf.Duration
}
var file_grpc_exec_grpc_exec_proto_depIdxs = []int32{
	1, // 0: grpc_exec.ClientEvent.start:type_name -> grpc_exec.StartCommandRequest
	2, // 1: grpc_exec.ClientEvent.terminate:type_name -> grpc_exec.TerminateCommand
	6, // 2: grpc_exec.TerminateCommand.grace_period:type_name -> google.protobuf.Duration
	5, // 3: grpc_exec.ServerEvent.exited:type_name -> grpc_exec.ExitInfo
	4, // 4: grpc_exec.ServerEvent.started:type_name -> grpc_exec.CommandStarted
	0, // 5: grpc_exec.ExecService.RunCommand:input_type -> grpc_exec.ClientEvent
	3, // 6: grpc_exec.ExecService.RunCommand:output_type -> grpc_exec.ServerEvent
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_grpc_exec_grpc_exec_proto_init() }
func file_grpc_exec_grpc_exec_proto_init() {
	if File_grpc_exec_grpc_exec_proto != nil {
		return
	}
	file_grpc_exec_grpc_exec_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientEvent_Start)(nil),
		(*ClientEvent_Terminate)(nil),
	}
	file_grpc_exec_grpc_exec_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerEvent_Output)(nil),
		(*ServerEvent_Exited)(nil),
		(*ServerEvent_Started)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_exec_grpc_exec_proto_rawDesc), len(file_grpc_exec_grpc_exec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_exec_grpc_exec_proto_goTypes,
		DependencyIndexes: file_grpc_exec_grpc_exec_proto_depIdxs,
		MessageInfos:      file_grpc_exec_grpc_exec_proto_msgTypes,
	}.Build()
	File_grpc_exec_grpc_exec_proto = out.File
	file_grpc_exec_grpc_exec_proto_goTypes = nil
	file_grpc_exec_grpc_exec_proto_depIdxs = nil
}
