// Auto-generated ESM wrapper for node:assert
import { getNodeApiModule, subscribeNodeApiModule } from '../node-api-surface.js';

let _defaultExport = getNodeApiModule('assert');
function _syncNodeApiModuleBindings() {
  const mod = getNodeApiModule('assert');
  _defaultExport = mod;
  Assert = mod.Assert;
  AssertionError = mod.AssertionError;
  CallTracker = mod.CallTracker;
  deepEqual = mod.deepEqual;
  deepStrictEqual = mod.deepStrictEqual;
  doesNotMatch = mod.doesNotMatch;
  doesNotReject = mod.doesNotReject;
  doesNotThrow = mod.doesNotThrow;
  equal = mod.equal;
  fail = mod.fail;
  ifError = mod.ifError;
  match = mod.match;
  notDeepEqual = mod.notDeepEqual;
  notDeepStrictEqual = mod.notDeepStrictEqual;
  notEqual = mod.notEqual;
  notStrictEqual = mod.notStrictEqual;
  ok = mod.ok;
  partialDeepStrictEqual = mod.partialDeepStrictEqual;
  rejects = mod.rejects;
  strict = mod.strict;
  strictEqual = mod.strictEqual;
  throws = mod.throws;
}
export let Assert;
export let AssertionError;
export let CallTracker;
export let deepEqual;
export let deepStrictEqual;
export let doesNotMatch;
export let doesNotReject;
export let doesNotThrow;
export let equal;
export let fail;
export let ifError;
export let match;
export let notDeepEqual;
export let notDeepStrictEqual;
export let notEqual;
export let notStrictEqual;
export let ok;
export let partialDeepStrictEqual;
export let rejects;
export let strict;
export let strictEqual;
export let throws;
export { _defaultExport as default };
_syncNodeApiModuleBindings();
subscribeNodeApiModule('assert', _syncNodeApiModuleBindings);
