// Auto-generated ESM wrapper for node:console
import { getNodeApiModule, subscribeNodeApiModule } from '../node-api-surface.js';

let _defaultExport = getNodeApiModule('console');
function _syncNodeApiModuleBindings() {
  const mod = getNodeApiModule('console');
  _defaultExport = mod;
  Console = mod.Console;
  assert = mod.assert;
  clear = mod.clear;
  context = mod.context;
  count = mod.count;
  countReset = mod.countReset;
  createTask = mod.createTask;
  debug = mod.debug;
  dir = mod.dir;
  dirxml = mod.dirxml;
  error = mod.error;
  group = mod.group;
  groupCollapsed = mod.groupCollapsed;
  groupEnd = mod.groupEnd;
  info = mod.info;
  log = mod.log;
  profile = mod.profile;
  profileEnd = mod.profileEnd;
  table = mod.table;
  time = mod.time;
  timeEnd = mod.timeEnd;
  timeLog = mod.timeLog;
  timeStamp = mod.timeStamp;
  trace = mod.trace;
  warn = mod.warn;
}
export let Console;
export let assert;
export let clear;
export let context;
export let count;
export let countReset;
export let createTask;
export let debug;
export let dir;
export let dirxml;
export let error;
export let group;
export let groupCollapsed;
export let groupEnd;
export let info;
export let log;
export let profile;
export let profileEnd;
export let table;
export let time;
export let timeEnd;
export let timeLog;
export let timeStamp;
export let trace;
export let warn;
export { _defaultExport as default };
_syncNodeApiModuleBindings();
subscribeNodeApiModule('console', _syncNodeApiModuleBindings);
