// Auto-generated ESM wrapper for node:os
import { getNodeApiModule, subscribeNodeApiModule } from '../node-api-surface.js';

let _defaultExport = getNodeApiModule('os');
function _syncNodeApiModuleBindings() {
  const mod = getNodeApiModule('os');
  _defaultExport = mod;
  EOL = mod.EOL;
  arch = mod.arch;
  availableParallelism = mod.availableParallelism;
  constants = mod.constants;
  cpus = mod.cpus;
  devNull = mod.devNull;
  endianness = mod.endianness;
  freemem = mod.freemem;
  getPriority = mod.getPriority;
  homedir = mod.homedir;
  hostname = mod.hostname;
  loadavg = mod.loadavg;
  machine = mod.machine;
  networkInterfaces = mod.networkInterfaces;
  platform = mod.platform;
  release = mod.release;
  setPriority = mod.setPriority;
  tmpdir = mod.tmpdir;
  totalmem = mod.totalmem;
  type = mod.type;
  uptime = mod.uptime;
  userInfo = mod.userInfo;
  version = mod.version;
}
export let EOL;
export let arch;
export let availableParallelism;
export let constants;
export let cpus;
export let devNull;
export let endianness;
export let freemem;
export let getPriority;
export let homedir;
export let hostname;
export let loadavg;
export let machine;
export let networkInterfaces;
export let platform;
export let release;
export let setPriority;
export let tmpdir;
export let totalmem;
export let type;
export let uptime;
export let userInfo;
export let version;
export { _defaultExport as default };
_syncNodeApiModuleBindings();
subscribeNodeApiModule('os', _syncNodeApiModuleBindings);
