// Auto-generated ESM wrapper for node:stream
import { getNodeApiModule, subscribeNodeApiModule } from '../node-api-surface.js';

let _defaultExport = getNodeApiModule('stream');
function _syncNodeApiModuleBindings() {
  const mod = getNodeApiModule('stream');
  _defaultExport = mod;
  Duplex = mod.Duplex;
  PassThrough = mod.PassThrough;
  Readable = mod.Readable;
  Stream = mod.Stream;
  Transform = mod.Transform;
  Writable = mod.Writable;
  addAbortSignal = mod.addAbortSignal;
  compose = mod.compose;
  destroy = mod.destroy;
  duplexPair = mod.duplexPair;
  finished = mod.finished;
  getDefaultHighWaterMark = mod.getDefaultHighWaterMark;
  isDestroyed = mod.isDestroyed;
  isDisturbed = mod.isDisturbed;
  isErrored = mod.isErrored;
  isReadable = mod.isReadable;
  isWritable = mod.isWritable;
  pipeline = mod.pipeline;
  promises = mod.promises;
  setDefaultHighWaterMark = mod.setDefaultHighWaterMark;
}
export let Duplex;
export let PassThrough;
export let Readable;
export let Stream;
export let Transform;
export let Writable;
export let addAbortSignal;
export let compose;
export let destroy;
export let duplexPair;
export let finished;
export let getDefaultHighWaterMark;
export let isDestroyed;
export let isDisturbed;
export let isErrored;
export let isReadable;
export let isWritable;
export let pipeline;
export let promises;
export let setDefaultHighWaterMark;
export { _defaultExport as default };
_syncNodeApiModuleBindings();
subscribeNodeApiModule('stream', _syncNodeApiModuleBindings);
