// Auto-generated ESM wrapper for node:v8
import { getNodeApiModule, subscribeNodeApiModule } from '../node-api-surface.js';

let _defaultExport = getNodeApiModule('v8');
function _syncNodeApiModuleBindings() {
  const mod = getNodeApiModule('v8');
  _defaultExport = mod;
  DefaultDeserializer = mod.DefaultDeserializer;
  DefaultSerializer = mod.DefaultSerializer;
  Deserializer = mod.Deserializer;
  GCProfiler = mod.GCProfiler;
  Serializer = mod.Serializer;
  cachedDataVersionTag = mod.cachedDataVersionTag;
  deserialize = mod.deserialize;
  getCppHeapStatistics = mod.getCppHeapStatistics;
  getHeapCodeStatistics = mod.getHeapCodeStatistics;
  getHeapSnapshot = mod.getHeapSnapshot;
  getHeapSpaceStatistics = mod.getHeapSpaceStatistics;
  getHeapStatistics = mod.getHeapStatistics;
  isStringOneByteRepresentation = mod.isStringOneByteRepresentation;
  promiseHooks = mod.promiseHooks;
  queryObjects = mod.queryObjects;
  serialize = mod.serialize;
  setFlagsFromString = mod.setFlagsFromString;
  setHeapSnapshotNearHeapLimit = mod.setHeapSnapshotNearHeapLimit;
  startCpuProfile = mod.startCpuProfile;
  startupSnapshot = mod.startupSnapshot;
  stopCoverage = mod.stopCoverage;
  takeCoverage = mod.takeCoverage;
  writeHeapSnapshot = mod.writeHeapSnapshot;
}
export let DefaultDeserializer;
export let DefaultSerializer;
export let Deserializer;
export let GCProfiler;
export let Serializer;
export let cachedDataVersionTag;
export let deserialize;
export let getCppHeapStatistics;
export let getHeapCodeStatistics;
export let getHeapSnapshot;
export let getHeapSpaceStatistics;
export let getHeapStatistics;
export let isStringOneByteRepresentation;
export let promiseHooks;
export let queryObjects;
export let serialize;
export let setFlagsFromString;
export let setHeapSnapshotNearHeapLimit;
export let startCpuProfile;
export let startupSnapshot;
export let stopCoverage;
export let takeCoverage;
export let writeHeapSnapshot;
export { _defaultExport as default };
_syncNodeApiModuleBindings();
subscribeNodeApiModule('v8', _syncNodeApiModuleBindings);
